1

diff --git a/.github/workflows/3.yml b/.github/workflows/3.yml
--- a/.github/workflows/3.yml
+++ b/.github/workflows/3.yml
@@ -231,6 +231,11 @@ jobs:
          rm -rf ./sched_ext/.git
          fi
 
+      - name: 拉取afdo
+        run: |
+          cd kernel_workspace/kernel_platform/
+          git clone https://$TOKEN@github.com/JiuGeFaCai/afdo.git
+
       - name: use LTO=thin
         if: ${{inputs.enable_lto }}
         run: |
@@ -247,6 +252,14 @@ jobs:
 
           export PATH="$GITHUB_WORKSPACE/kernel_workspace/kernel_platform/prebuilts/clang/host/linux-x86/clang-r510928/bin:$PATH"
           export PATH="/usr/lib/ccache:$PATH"
+          
+          # 设置 AFDO 配置文件路径
+          export AFDO_PROFILE="${{ github.workspace }}/kernel_workspace/kernel_platform/afdo/kernel.afdo"
+          if [ ! -f "$AFDO_PROFILE" ]; then
+           echo "Error: AFDO profile not found at $AFDO_PROFILE"
+          exit 1
+          fi
+
           cd kernel_workspace/kernel_platform/common
 
           git clone https://$TOKEN@github.com/JiuGeFaCai/kernel.afdo.git
@@ -258,7 +271,7 @@ jobs:
           echo "Checking if ThinLTO was applied:"
           find out/ -name '*.cmd' | xargs grep -E '\-flto(=thin)?' | head
           else
-          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC='ccache clang' RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld  HOSTLD=ld.lld O=out KCFLAGS+=-Wno-error gki_defconfig all
+          make -j$(nproc --all) LLVM=1 ARCH=arm64 CROSS_COMPILE=aarch64-linux-gnu- CC='ccache clang' RUSTC=../../prebuilts/rust/linux-x86/1.73.0b/bin/rustc PAHOLE=../../prebuilts/kernel-build-tools/linux-x86/bin/pahole LD=ld.lld  HOSTLD=ld.lld O=out KCFLAGS+="-Wno-error -fauto-profile=$AFDO_PROFILE" gki_defconfig all
           fi
           # 创建输出目录并复制 Image
           mkdir -p ../dist
